import type { Dimension } from './types';

export const STYLE_DIMENSIONS: Dimension[] = [

  // ── STRUCTURAL FLOW ──────────────────────────────────────────────────────
  {
    name: 'Sequential Events',
    group: 'Structural Flow',
    type: 'spectrum',
    pole_low: 'The Integrator',
    pole_high: 'The Sequencer',
    low_desc: 'Integrates sequential steps within a single sentence using commas, semicolons, or conjunctions',
    high_desc: 'Separates sequential steps into distinct sentences with explicit markers (First, Then, Finally) or numbered lists',
  },
  {
    name: 'Process Steps',
    group: 'Structural Flow',
    type: 'spectrum',
    pole_low: 'The Commander',
    pole_high: 'The Proceduralist',
    low_desc: 'Presents process steps as an integrated imperative or comma list',
    high_desc: 'Presents each step in passive or nominalized form as a separate sequence',
  },
  {
    name: 'Information Ordering',
    group: 'Structural Flow',
    type: 'spectrum',
    pole_low: 'The Scene-Setter',
    pole_high: 'The Headliner',
    low_desc: 'Leads with the challenge or context before stating the main point or result',
    high_desc: 'Leads with the main point or result, then provides context or qualifications',
  },
  {
    name: 'Main Point Placement',
    group: 'Structural Flow',
    type: 'spectrum',
    pole_low: 'The Builder',
    pole_high: 'The Front-Loader',
    low_desc: 'Builds up to the main point rather than leading with it (inductive, back-loaded)',
    high_desc: 'States the main point at the beginning of paragraphs or sections (deductive, front-loaded)',
  },
  {
    name: 'Action Sequences',
    group: 'Structural Flow',
    type: 'spectrum',
    pole_low: 'The Parallelist',
    pole_high: 'The Chainer',
    low_desc: 'Presents action sequences as parallel comma lists',
    high_desc: 'Presents actions as a subordinate chain',
  },
  {
    name: 'Sequential Relationships',
    group: 'Structural Flow',
    type: 'spectrum',
    pole_low: 'The Atomist',
    pole_high: 'The Synthesizer',
    low_desc: 'Uses short, separate declarative sentences for sequences',
    high_desc: 'Integrates sequences into a complex sentence with subordinate clauses',
  },
  {
    name: 'Chronological vs Importance',
    group: 'Structural Flow',
    type: 'spectrum',
    pole_low: 'The Chronicler',
    pole_high: 'The Strategist',
    low_desc: 'Organizes information in chronological order',
    high_desc: 'Organizes by importance or impact rather than time',
  },
  {
    name: 'Organization patterns',
    group: 'Structural Flow',
    type: 'categorical',
    A: 'Prefers to lead with the main point and explain it (deductive).',
    B: 'Prefers to build up to the main point gradually (inductive).',
    C: 'Adjusts structure based on context and audience.',
  },
  {
    name: 'Section/argument structuring',
    group: 'Structural Flow',
    type: 'categorical',
    A: 'Uses a clear, linear progression of arguments.',
    B: 'Prefers thematic or circular structures that revisit key points.',
    C: 'Tends to use a hybrid or fluid structure.',
  },
  {
    name: 'Paragraph structures',
    group: 'Structural Flow',
    type: 'categorical',
    A: 'Follows traditional topic-sentence structure.',
    B: 'Writes freeform or fluid paragraphs.',
    C: 'Shifts styles based on section and purpose.',
  },

  // ── CAUSALITY & LOGIC ────────────────────────────────────────────────────
  {
    name: 'Cause and Effect',
    group: 'Causality & Logic',
    type: 'spectrum',
    pole_low: 'The Linker',
    pole_high: 'The Separator',
    low_desc: 'Integrates cause and effect within a single sentence using connective phrases',
    high_desc: 'Separates cause and effect across multiple sentences',
  },
  {
    name: 'Cause Before/After Effect',
    group: 'Causality & Logic',
    type: 'spectrum',
    pole_low: 'The Explainer',
    pole_high: 'The Revealer',
    low_desc: 'Typically places the cause before the effect',
    high_desc: 'Typically places the effect before the cause',
  },
  {
    name: 'Purposeful Relationships',
    group: 'Causality & Logic',
    type: 'spectrum',
    pole_low: 'The Implicator',
    pole_high: 'The Crystalizer',
    low_desc: 'Uses simple coordination to connect related actions — purpose is implied',
    high_desc: 'Uses explicit purpose markers (to, in order to) to crystallize intent',
  },
  {
    name: 'Conditional Relationships',
    group: 'Causality & Logic',
    type: 'spectrum',
    pole_low: 'The Integrator',
    pole_high: 'The Conditionalist',
    low_desc: 'Integrates conditional relationships within single sentences',
    high_desc: 'Separates conditional elements into distinct sentences',
  },
  {
    name: 'Condition Before/After Result',
    group: 'Causality & Logic',
    type: 'spectrum',
    pole_low: 'The Setter',
    pole_high: 'The Debtor',
    low_desc: 'States the condition before the result (if… then…)',
    high_desc: 'States the result before the condition (outcome first, conditions follow)',
  },
  {
    name: 'Context Before/After Action',
    group: 'Causality & Logic',
    type: 'spectrum',
    pole_low: 'The Contextualist',
    pole_high: 'The Actionist',
    low_desc: 'Provides context before stating the action',
    high_desc: 'States the action before providing context',
  },
  {
    name: 'Contrasting Relationships',
    group: 'Causality & Logic',
    type: 'spectrum',
    pole_low: 'The Harmonist',
    pole_high: 'The Contrarian',
    low_desc: "Uses 'yet' or additive conjunctions — emphasises coexistence over tension",
    high_desc: "Uses 'while' or contrastive subordination — emphasises the tension",
  },
  {
    name: 'Causal',
    group: 'Causality & Logic',
    type: 'spectrum',
    pole_low: 'The Coordinator',
    pole_high: 'The Logician',
    low_desc: 'Uses simple coordination for causal links (so, and)',
    high_desc: 'Uses subordination for causal links (because, since)',
  },
  {
    name: 'Problem-Solution',
    group: 'Causality & Logic',
    type: 'spectrum',
    pole_low: 'The Synthesizer',
    pole_high: 'The Analyst',
    low_desc: 'Integrates problem and solution within a single complex sentence',
    high_desc: 'Separates problem and solution across multiple sentences',
  },

  // ── TONE & VOICE ─────────────────────────────────────────────────────────
  {
    name: 'Use of interjections',
    group: 'Tone & Voice',
    type: 'spectrum',
    pole_low: 'The Understater',
    pole_high: 'The Illustrator',
    low_desc: 'Uses softer, more conventional interjections (Well, Now)',
    high_desc: 'Uses vivid, distinctive interjections (Ah, But wait)',
  },
  {
    name: 'Sentence adverbs and stance',
    group: 'Tone & Voice',
    type: 'spectrum',
    pole_low: 'The Director',
    pole_high: 'The Annotator',
    low_desc: 'States position without stance adverbs — direct and unqualified',
    high_desc: 'Uses explicit stance markers (Frankly, Honestly, Clearly) to annotate position',
  },
  {
    name: 'Temporal nuance and tone',
    group: 'Tone & Voice',
    type: 'categorical',
    A: "Uses 'still' to convey mild frustration or expectation — e.g. 'He still hasn't responded.'",
    B: "Uses 'yet' for neutral temporal marking — e.g. 'He hasn't responded yet.'",
    C: "Uses em-dash for dramatic effect — e.g. 'He hasn't responded—already!'",
    D: "Uses parenthetical for resigned or sardonic tone — e.g. 'He hasn't responded (again).'",
  },
  {
    name: 'Use of emphasis for tone',
    group: 'Tone & Voice',
    type: 'spectrum',
    pole_low: 'The Wordsmith',
    pole_high: 'The Highlighter',
    low_desc: 'Relies on word choice and placement rather than typographic emphasis',
    high_desc: 'Uses typographic emphasis (*word*, italics, caps) to stress key points',
  },
  {
    name: 'How to introduce counterarguments',
    group: 'Tone & Voice',
    type: 'categorical',
    A: 'Acknowledges counterarguments early to build credibility.',
    B: 'Introduces counterarguments only when strictly necessary.',
    C: 'Weaves counterarguments into the main argument fluidly without announcing them.',
  },
  {
    name: 'Tone of interpersonal address',
    group: 'Tone & Voice',
    type: 'categorical',
    A: "Uses direct, authoritative address — e.g. 'I urge you to reconsider your approach.'",
    B: "Uses suggestive, collaborative address — e.g. 'You might want to take another look at this.'",
    C: "Uses inclusive, conversational address — e.g. 'Let's reflect on this together, shall we?'",
    D: "Uses informal, take-it-or-leave-it address — e.g. 'Here's my take—do with it what you will.'",
  },
  {
    name: 'Preferred tone in conveying contrast',
    group: 'Tone & Voice',
    type: 'spectrum',
    pole_low: 'The Coexister',
    pole_high: 'The Confronter',
    low_desc: 'Uses additive conjunctions even when contrasting (and) — emphasises coexistence',
    high_desc: 'Uses contrastive conjunctions (but) — emphasises the tension',
  },
  {
    name: 'Emphasis',
    group: 'Tone & Voice',
    type: 'spectrum',
    pole_low: 'The Plainspeaker',
    pole_high: 'The Claimer',
    low_desc: 'Uses direct, unadorned statement for emphasis',
    high_desc: 'Uses cleft sentences for emphasis (It was X that drove the change...)',
  },
  {
    name: 'Use of emphasis and sentence force',
    group: 'Tone & Voice',
    type: 'categorical',
    A: "Uses blunt, minimal constructions for force — e.g. 'This matters. Period.'",
    B: "Uses ellipsis or building constructions — e.g. 'This... really does matter.'",
    C: "Uses dramatic, declarative constructions — e.g. 'And this, above all else, truly matters:'",
    D: "Uses formal, measured constructions — e.g. 'It does matter, indeed.'",
  },
  {
    name: 'Sensitivity to audience or context',
    group: 'Tone & Voice',
    type: 'categorical',
    A: 'Defaults to formal, institutional register.',
    B: 'Uses direct, casual register.',
    C: 'Adapts explicitly to professional audience.',
    D: 'Uses intimate or social register.',
  },
  {
    name: 'Use of irony or dry humor',
    group: 'Tone & Voice',
    type: 'categorical',
    A: "Uses understated/deadpan irony — e.g. 'Well, that went exactly as planned…'",
    B: 'Uses matter-of-fact understatement.',
    C: 'Uses distancing/wry tone.',
    D: 'Uses sardonic/pointed irony.',
  },
  {
    name: 'Emotional proximity',
    group: 'Tone & Voice',
    type: 'spectrum',
    pole_low: 'The Reporter',
    pole_high: 'The Empath',
    low_desc: 'Clinical or detached — reports events at a distance without emotional immersion',
    high_desc: 'Intense and immersive — writes with deep emotional proximity to subject matter',
  },
  {
    name: 'Personal vs impersonal',
    group: 'Tone & Voice',
    type: 'spectrum',
    pole_low: 'The Subjecter',
    pole_high: 'The Narrator',
    low_desc: 'Tends to write impersonally, focusing on the subject matter',
    high_desc: 'Often uses personal pronouns and speaks from own perspective (I, we, our)',
  },
  {
    name: 'Formal vs conversational',
    group: 'Tone & Voice',
    type: 'spectrum',
    pole_low: 'The Traditionalist',
    pole_high: 'The Conversationalist',
    low_desc: 'Usually writes in a formal and professional register',
    high_desc: 'Prefers a relaxed, conversational tone',
  },

  // ── VOCABULARY & LANGUAGE ────────────────────────────────────────────────
  {
    name: 'Preference for poetic vs plain',
    group: 'Vocabulary & Language',
    type: 'spectrum',
    pole_low: 'The Pragmatist',
    pole_high: 'The Poet',
    low_desc: 'Uses plain, contemporary language',
    high_desc: 'Uses poetic, archaic, or elevated language',
  },
  {
    name: 'Preference for taboo or plain register',
    group: 'Vocabulary & Language',
    type: 'spectrum',
    pole_low: 'The Tactician',
    pole_high: 'The Bulldozer',
    low_desc: 'Uses euphemistic or tactful alternatives — avoids blunt or taboo language',
    high_desc: 'Uses precise or frank language even when taboo or uncomfortable',
  },
  {
    name: 'Sensitivity to pejorative tone',
    group: 'Vocabulary & Language',
    type: 'spectrum',
    pole_low: 'The Balancer',
    pole_high: 'The Inflamer',
    low_desc: 'Uses neutral, descriptive language — avoids charged or evaluative words',
    high_desc: 'Uses charged, evaluative language when available',
  },
  {
    name: 'Evocative vs Neutral language',
    group: 'Vocabulary & Language',
    type: 'spectrum',
    pole_low: 'The Journalist',
    pole_high: 'The Painter',
    low_desc: 'Uses neutral, denotative language',
    high_desc: 'Uses evocative, sensory language',
  },
  {
    name: 'Formality in vocabulary',
    group: 'Vocabulary & Language',
    type: 'spectrum',
    pole_low: 'The Peer',
    pole_high: 'The Scholar',
    low_desc: 'Uses informal or colloquial vocabulary — speaks as an equal',
    high_desc: 'Uses formal, elevated, or professional vocabulary',
  },
  {
    name: 'Complex vs simple vocabulary',
    group: 'Vocabulary & Language',
    type: 'categorical',
    A: 'Tends to use precise, sometimes complex words.',
    B: 'Chooses words that are simple and accessible.',
    C: 'Adapts based on clarity and impact.',
  },
  {
    name: 'Use of specialized terminology',
    group: 'Vocabulary & Language',
    type: 'categorical',
    A: 'Uses domain-specific terms confidently without defining them.',
    B: 'Avoids jargon and explains all terms clearly.',
    C: 'Uses specialized terms with brief inline definitions.',
  },
  {
    name: 'Technical vs plain language',
    group: 'Vocabulary & Language',
    type: 'categorical',
    A: 'Writes with technical accuracy and specificity.',
    B: 'Translates complex ideas into plain language.',
    C: "Shifts based on the audience's familiarity.",
  },
  {
    name: 'Abstract vs concrete examples',
    group: 'Vocabulary & Language',
    type: 'spectrum',
    pole_low: 'The Realist',
    pole_high: 'The Theorist',
    low_desc: 'Relies on concrete, relatable examples',
    high_desc: 'Prefers abstract or theoretical illustrations',
  },
  {
    name: 'Inventiveness and creative expression',
    group: 'Vocabulary & Language',
    type: 'categorical',
    A: 'Invents language or uses dense jargon creatively.',
    B: 'Uses plain, no-nonsense expression.',
    C: 'Coins memorable, original phrases.',
    D: 'Uses unexpectedly vivid or figurative language.',
  },

  // ── GRAMMAR & SYNTAX ─────────────────────────────────────────────────────
  {
    name: 'Sentence Complexity',
    group: 'Grammar & Syntax',
    type: 'spectrum',
    pole_low: 'The Minimalist',
    pole_high: 'The Maximalist',
    low_desc: 'Favours short, separate sentences — lean and direct',
    high_desc: 'Favours multi-clause integrated sentences — expansive and embedded',
  },
  {
    name: 'Modifier Placement',
    group: 'Grammar & Syntax',
    type: 'spectrum',
    pole_low: 'The Inliner',
    pole_high: 'The Preempter',
    low_desc: 'Places modifiers after the verb or within the main clause',
    high_desc: 'Places modifying phrases before the main clause (fronted participles)',
  },
  {
    name: 'Verb Forms',
    group: 'Grammar & Syntax',
    type: 'spectrum',
    pole_low: 'The Action-Taker',
    pole_high: 'The Nominalizer',
    low_desc: 'Uses active, parallel verb constructions',
    high_desc: 'Uses nominalized or copula constructions (turns verbs into nouns)',
  },
  {
    name: 'Parallelism',
    group: 'Grammar & Syntax',
    type: 'spectrum',
    pole_low: 'The Verb-Builder',
    pole_high: 'The Noun-Builder',
    low_desc: 'Uses parallel verb-based structures',
    high_desc: 'Uses parallel noun-based or adjectival structures',
  },
  {
    name: 'Active vs Passive Voice',
    group: 'Grammar & Syntax',
    type: 'spectrum',
    pole_low: 'The Observer',
    pole_high: 'The Actor',
    low_desc: 'Uses passive voice — emphasises results or objectivity',
    high_desc: 'Strongly prefers active voice — direct and agent-led',
  },
  {
    name: 'Coordination vs. Subordination',
    group: 'Grammar & Syntax',
    type: 'spectrum',
    pole_low: 'The Coordinator',
    pole_high: 'The Subordinator',
    low_desc: 'Prefers coordination to connect clauses (but, and)',
    high_desc: 'Prefers subordination to connect clauses (while, although)',
  },
  {
    name: 'Temporal Relationships',
    group: 'Grammar & Syntax',
    type: 'spectrum',
    pole_low: 'The Supplementer',
    pole_high: 'The Anchor',
    low_desc: 'Uses coordination for temporal links (and then)',
    high_desc: 'Uses subordination for temporal links (when, after)',
  },
  {
    name: 'List Structures',
    group: 'Grammar & Syntax',
    type: 'spectrum',
    pole_low: 'The Action-Lister',
    pole_high: 'The Concept-Lister',
    low_desc: 'Uses verb-parallel or gerund-based lists',
    high_desc: 'Uses noun-phrase lists',
  },
  {
    name: 'Comparative Elements',
    group: 'Grammar & Syntax',
    type: 'spectrum',
    pole_low: 'The Separator',
    pole_high: 'The Weaver',
    low_desc: 'Presents comparative elements as short, separate statements',
    high_desc: 'Integrates comparisons into complex sentences',
  },
  {
    name: 'Rhythm and sentence flow',
    group: 'Grammar & Syntax',
    type: 'spectrum',
    pole_low: 'The Orator',
    pole_high: 'The Storyteller',
    low_desc: 'Uses tricolon, anaphora, or parallel cadence for rhetorical rhythm',
    high_desc: 'Uses expanded, natural prose flow',
  },

  // ── RHETORIC & EVIDENCE ──────────────────────────────────────────────────
  {
    name: 'Ways to incorporate evidence',
    group: 'Rhetoric & Evidence',
    type: 'categorical',
    A: 'Cites data and examples to back every point.',
    B: 'Uses evidence selectively for emphasis.',
    C: 'Balances logic, evidence, and persuasion.',
  },
  {
    name: 'Methods for defining terms',
    group: 'Rhetoric & Evidence',
    type: 'categorical',
    A: 'Defines key terms explicitly at the start.',
    B: 'Defines terms as they naturally arise.',
    C: 'Relies on context to make meaning clear.',
  },
  {
    name: 'Handling of citations/references',
    group: 'Rhetoric & Evidence',
    type: 'categorical',
    A: 'Follows a consistent academic citation format.',
    B: 'References casually or narratively.',
    C: 'Uses citations where required, but focuses on flow.',
  },
  {
    name: 'Direct vs hedged statements',
    group: 'Rhetoric & Evidence',
    type: 'spectrum',
    pole_low: 'The Oracle',
    pole_high: 'The Diplomat',
    low_desc: 'States claims directly and assertively',
    high_desc: 'Tends to hedge statements with qualifiers',
  },
  {
    name: 'Approaches to conclusions',
    group: 'Rhetoric & Evidence',
    type: 'categorical',
    A: 'Summarises key points and restates the argument.',
    B: 'Closes with a memorable or emotional appeal.',
    C: 'Prefers open-ended or reflective endings.',
  },
  {
    name: 'Comparative Analysis',
    group: 'Rhetoric & Evidence',
    type: 'spectrum',
    pole_low: 'The Fragmenter',
    pole_high: 'The Integrator',
    low_desc: 'Separates comparisons across sentences',
    high_desc: 'Integrates comparisons using subordinate clauses',
  },

  // ── PRESENTATION & FORMAT ────────────────────────────────────────────────
  {
    name: 'Transitional devices',
    group: 'Presentation & Format',
    type: 'spectrum',
    pole_low: 'The Thinker',
    pole_high: 'The Guide',
    low_desc: 'Prefers implicit transitions — trusts the reader to follow the flow',
    high_desc: 'Uses clear, explicit linking words and phrases',
  },
  {
    name: 'Frequency of transitional phrases',
    group: 'Presentation & Format',
    type: 'spectrum',
    pole_low: 'The Cluemaster',
    pole_high: 'The Signposter',
    low_desc: 'Uses transitions sparingly, trusting the flow of ideas',
    high_desc: 'Uses transitions frequently to guide the reader',
  },
  {
    name: 'Formatting preferences',
    group: 'Presentation & Format',
    type: 'spectrum',
    pole_low: 'The Prose-Writer',
    pole_high: 'The Architect',
    low_desc: 'Prefers minimal formatting and flowing prose',
    high_desc: 'Uses headings, lists, and bold to organise content',
  },
  {
    name: 'Punctuation patterns',
    group: 'Presentation & Format',
    type: 'categorical',
    A: 'Uses punctuation rigorously to clarify structure.',
    B: 'Punctuates based on rhythm and tone.',
    C: 'Varies punctuation depending on formality.',
  },
];

export const DIMENSION_GROUPS = [
  'Structural Flow',
  'Causality & Logic',
  'Tone & Voice',
  'Vocabulary & Language',
  'Grammar & Syntax',
  'Rhetoric & Evidence',
  'Presentation & Format',
] as const;

export type DimensionGroup = typeof DIMENSION_GROUPS[number];

export function buildDimensionReference(): string {
  const lines: string[] = [];
  let currentGroup = '';

  for (const dim of STYLE_DIMENSIONS) {
    if (dim.group !== currentGroup) {
      currentGroup = dim.group;
      lines.push(`\n[${currentGroup.toUpperCase()}]`);
    }

    if (dim.type === 'spectrum') {
      const low = dim.low_desc.length > 85 ? dim.low_desc.slice(0, 85) + '...' : dim.low_desc;
      const high = dim.high_desc.length > 85 ? dim.high_desc.slice(0, 85) + '...' : dim.high_desc;
      lines.push(
        `• ${dim.name} [SPECTRUM 0–100] | 0=${dim.pole_low}: ${low} | 100=${dim.pole_high}: ${high}`
      );
    } else {
      const opts = Object.entries(dim)
        .filter(([k]) => !['name', 'group', 'type'].includes(k))
        .map(([k, v]) => {
          const s = String(v);
          return `${k}=${s.length > 70 ? s.slice(0, 70) + '...' : s}`;
        })
        .join(' | ');
      lines.push(`• ${dim.name} [CATEGORICAL]: ${opts}`);
    }
  }

  return lines.join('\n');
}
